version: 2
updates:
  - package-ecosystem: "npm"
    assignees:
      - "presspausegarage"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
